# Site Settings
name: ThePrompt.Ninja
title: ThePrompt.Ninja | Prompt examples for beginner to Xpert ChatGPT and Image Generation 
description: ThePrompt.Ninja your main source to ease your life and save time. Be more productive
tags:
  - A.I.
  - Prompts
  - Make life easier with A.I.
  - Productivity
  - Information
show_hero: false
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: How to
    url: /howto
  - title: Prompt
    url: /prompt
  - title: Blog
    url: /blog
  - title: Privacy
    url: /privacy/
  - title: Contact
    url: /contact
#  - title: Feed
#    url: /feed.xml
email: r.murrell@hotmail.de
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: mvongyzj


# Social Media Settings
# Remove the item if you don't need it
github_username: asyncsan
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
#baseurl: "/promptlab.github.io" # the subpath of your site, e.g. /blog
baseurl: ""
url: "https://theprompt.ninja" # the base hostname & protocol for your site
google_analytics: "G-FN378MDZD2"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
#permalink: pretty
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: true

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: /:categories/:title/
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
  - jekyll-toc

# TOC Settings
toc:
  min_level: 1
  max_level: 3
  list_class: toc
  list_class: toc__list
  sublist_class: toc__sublist


# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v3.1.2
mobile: false
