name: ThePrompt.Ninja
title: ThePrompt.Ninja | Prompt examples for beginner to Xpert ChatGPT and Image Generation 
description: ThePrompt.Ninja your main source to ease your life and save time. Be more productive
tags:
  - Prompt
  - A.I.
  - Artificial Intelligence
  - Easy life
  - Better work
  - more productivity
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: r.murrell@hotmail.de
# See: https://disqus.com/
#disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: mvongyzj
